### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by matulkum**

### CODE REVIEW

**Comment by agustin107** [comment]
Hi! Thanks for contributing.

Can you give us a context where this is happening?

**Comment by matulkum** [comment]
Hi,

well.. it happens always when `TextWidget` is used. The variable `name` simply does not exist in this context. So you get an *ReferenceError: name is not defined* error.

Seems to be obvious (even without context) given the source code of _TextWidget.tsx_ is pretty short ;)

Code to reproduce:

```typescript
import { Container } from '@material-ui/core'
import React from 'react'
import Form, { withTheme } from 'react-jsonschema-form'
import { Theme as MuiFormTheme }from 'rjsf-material-ui'

const MuiForm = withTheme(MuiFormTheme)

const schema = {
  title: 'Image',
  type: 'object' as 'object',
  required: [],
  properties: {
    name: {
      title: 'Name',
      name: 'Name',
      type: 'string' as 'string',
    },
  }
}

const Home = () => (
  <Container>
    <h1>There u go!</h1>
    <MuiForm schema={schema}></MuiForm>
  </Container>
)
```

To be honest, I do not really know, if `name` is needed or retrievable in some way. This was my first test with _react-jsonschema-form_ and I did not investigate deeply, but I am sure trying to access it results in an js error.

I am wondering how I am the first to encounter this. `TextWidget` must be probably the most used field in a form, no? Maybe this is a silent error when using js instead of typescript?

**Comment by agustin107** [comment]
I was testing with the code that described on your comment but I couldn't reproduce the error.

You can look the test here: [CodeSandbox](https://codesandbox.io/s/rjsf-material-uiissue-81-cznlo?fontsize=14)

Can you send a CodeSandbox URL that shows this issue? Thanks!

**Comment by matulkum** [comment]
@agustin107 I think the error might be "silent" when using js.

But to be honest: Just check the code in file *TextWidget.tsx, line 44* , and u can see it cannot be right:
```typescript
<TextField
        id={id}
        label={label || schema.title}
        autoFocus={autofocus}
        required={required}
        disabled={disabled || readonly}
        name={name} // line 44
        type={schema.type as string}
        value={value ? value : ''}
        onChange={_onChange}
        onBlur={_onBlur}
        onFocus={_onFocus}
      />
```

Where is the variable `name` suppose to be declared? It clearly **does not exist** anywhere in this function.

**Comment by matulkum** [comment]
.. allright. How about that then: Open the repo in vscode and hover over `name` to get its type. You will see that:

Screenshot 2019-10-23 at 18 35 54

It is typed `never`.. because it never has a value. Apparently the reason the typescript compiler is not complaining is because of setting `"lib": ["dom", "esnext"],` in _tsconfig.json_. Apprently `name` is defined in _lib.dom.d.ts_ as a global variable. So the error is not picked up.

My guess is in Browser `name` simply resolved to `undefined`, and nothing happens (So the line is useless anyways). But on server rendering (I am using *nextjs*) it fails though, with this error:

Screenshot 2019-10-23 at 18 41 17

**Comment by agustin107** [comment]
Oh, now I see the mistake! 

Instead of comment the line, can you delete it?

**Comment by agustin107** [comment]
> .. allright. How about that then: Open the repo in vscode and hover over `name` to get its type. You will see that:
> 
> Screenshot 2019-10-23 at 18 35 54
> 
> It is typed `never`.. because it never has a value. Apparently the reason the typescript compiler is not complaining is because of setting `"lib": ["dom", "esnext"],` in _tsconfig.json_. Apprently `name` is defined in _lib.dom.d.ts_ as a global variable. So the error is not picked up.
> 
> My guess is in Browser `name` simply resolved to `undefined`, and nothing happens (So the line is useless anyways). But on server rendering (I am using _nextjs_) it fails though, with this error:
> 
> Screenshot 2019-10-23 at 18 41 17

Yes! You're right, that was I saw it. Hmmm, interesting!

Thanks for your report!

**Pull request merged**
